#!/bin/bash -e

LIB=/usr/local/lib
SHARE=/usr/local/share
SRC=/usr/local/src

cd $SRC

# unpack Electron Cash
tar -zxf Electron*.tar.gz
rm Electron*.tar.gz

# install Electron Cash
mv Electron*/ $SHARE/electron-cash/
sudo ln -s $SHARE/electron-cash/electron-cash /usr/local/bin/electron-cash
sudo chmod +x /usr/local/bin/electron-cash

# unpack electrum-LTC
tar -zxf Electrum-LTC-*.tar.gz
rm Electrum-LTC-*.tar.gz

# install electrum-LTC
mv Electrum-LTC-*/ $SHARE/electrum-ltc/
sudo ln -s $SHARE/electrum-ltc/electrum-ltc /usr/local/bin/electrum-ltc
sudo chmod +x /usr/local/bin/electrum-ltc

# unpack electrum
tar -zxf Electrum-*.tar.gz
rm Electrum-*.tar.gz

# install electrum
mv Electrum-*/ $SHARE/electrum/
sudo ln -s $SHARE//electrum/electrum /usr/local/bin/electrum
sudo chmod +x /usr/local/bin/electrum

# unpack Exodus
unzip exodus-*.zip -d .
rm exodus-*.zip

# install Exodus
mv Exodus-*/ $LIB/exodus/
sudo ln -s $LIB/exodus/Exodus /usr/local/bin/exodus
sudo chmod +x /usr/local/bin/exodus

# unpack CryptoSeed
unzip CryptoSeed*.zip
rm CryptoSeed*.zip

# install CryptoSeed
mv CryptoSeed*/ $LIB/cryptoseed/
sudo ln -s $LIB/cryptoseed/cryptoseed /usr/local/bin/cryptoseed
sudo chmod +x /usr/local/bin/cryptoseed

# unpack electrum-dash
unzip electrum-dash*.zip
rm electrum-dash*.zip
mv electrum-dash-master/ electrum-dash/
unzip electrum-2.9.3-packages.zip
mv packages/ electrum-dash/packages/
rm electrum-2.9.3-packages.zip

# install electrum-dash
pyrcc4 electrum-dash/icons.qrc -o electrum-dash/gui/qt/icons_rc.py
mv electrum-dash/ $SHARE/electrum-dash/
sudo ln -s $SHARE/electrum-dash/electrum /usr/local/bin/electrum-dash
sudo chmod +x /usr/local/bin/electrum-dash

cd $SHARE

# copy dependencies from Electrum to Electron Cash
# mkdir electron-cash/packages/
# cp electrum/packages/* electron-cash/packages/ -R
# pyrcc5 electron-cash/icons.qrc -o electron-cash/gui/qt/icons_rc.py

# mkdir electrum-ltc/packages/
# cp electrum/packages/* electrum-ltc/packages/ -R
# pyrcc5 electrum-ltc/icons.qrc -o electrum-ltc/gui/qt/icons_rc.py