#!/bin/bash -e

SRC=/usr/local/src

cd $SRC

unzip *chrome-linux.zip
rm *chrome-linux.zip
sudo cp -rlf chrome-linux/* /usr/lib/chromium/
rm -rf chrome-linux/
sudo mv /usr/lib/chromium/chrome /usr/lib/chromium/chromium
sudo chmod +x /usr/lib/chromium/chromium
sudo chmod -R a+r /usr/lib/chromium/