#!/bin/bash -e

# update gsettings with customizations
glib-compile-schemas /usr/share/glib-2.0/schemas

# update db for overlayed desktop files
update-desktop-database

# set permissions on user's home
chown -R user:user /home/user
