#!/bin/bash -e

SRC=/usr/local/src

cd $SRC

# unpack electrum-LTC
tar -zxf Electrum-LTC-*.tar.gz
rm Electrum-LTC-*.tar.gz

# install electrum-LTC
cd Electrum-LTC-*
sudo ln -s electrum-ltc /usr/bin/electrum-ltc
# python3 setup.py install
cd -
# rm -rf Electrum-LTC-*/

# unpack Electron Cash
tar -zxf Electron-*.tar.gz
rm Electron-*.tar.gz
mv Electron*/ electron-cash/

# install Electron Cash
cd electron-*
sudo ln -s electron-cash /usr/bin/electron-cash
# python3 setup.py install
cd -
# rm -rf electron-*/

# unpack electrum
tar -zxf Electrum-*.tar.gz
rm Electrum-*.tar.gz

# install electrum
cd Electrum-*
python3 setup.py install
cd -
# rm -rf Electrum-*/

#fix protobuf permission
chmod -R a+r /usr/local/lib/python3.4/dist-packages/protobuf*