#!/bin/bash -e

SRC=/usr/local/src

cd $SRC

# unpack electrum-LTC
tar -zxf Electrum-LTC-*.tar.gz
rm Electrum-LTC-*.tar.gz

# install electrum-LTC
mv Electrum-LTC-*/ electrum-ltc/
sudo ln -s $SRC/electrum-ltc/electrum-ltc /usr/local/bin/electrum-ltc
sudo chmod +x /usr/local/bin/electrum-ltc
#cd Electrum-LTC-*
# python3 setup.py install
#cd -
# rm -rf Electrum-LTC-*/

# unpack Electron Cash
tar -zxf Electron-*.tar.gz
rm Electron-*.tar.gz

# install Electron Cash
mv Electron*/ electron-cash/
sudo ln -s $SRC/electron-cash/electron-cash /usr/local/bin/electron-cash
sudo chmod +x /usr/local/bin/electron-cash
#cd electron-*
# python3 setup.py install
#cd -
# rm -rf electron-*/

# unpack electrum
tar -zxf Electrum-*.tar.gz
rm Electrum-*.tar.gz

# install electrum
mv Electrum-*/ electrum/
sudo ln -s $SRC/electrum/electrum /usr/local/bin/electrum
sudo chmod +x /usr/local/bin/electrum
#cd Electrum-*
#python3 setup.py install
#cd -
# rm -rf Electrum-*/

#fix protobuf permission
#chmod -R a+r /usr/local/lib/python3.4/dist-packages/protobuf*