#!/bin/bash -e

SRC=/usr/local/src

cd $SRC

# unpack electrum-LTC
unzip electrum-ltc-*.zip
rm electrum-ltc-*.zip

# install electrum-LTC
mv electrum-ltc-*/ electrum-ltc/
sudo ln -s $SRC/electrum-ltc/electrum-ltc /usr/local/bin/electrum-ltc
sudo chmod +x /usr/local/bin/electrum-ltc

# unpack Electron Cash
tar -zxf Electron-*.tar.gz
rm Electron-*.tar.gz

# install Electron Cash
mv Electron*/ electron-cash/
sudo ln -s $SRC/electron-cash/electron-cash /usr/local/bin/electron-cash
sudo chmod +x /usr/local/bin/electron-cash

# unpack electrum
tar -zxf Electrum-*.tar.gz
rm Electrum-*.tar.gz

# install electrum
mv Electrum-*/ electrum/
sudo ln -s $SRC/electrum/electrum /usr/local/bin/electrum
sudo chmod +x /usr/local/bin/electrum

# unpack Exodus
unzip exodus-linux-x64-*.zip -d .
rm exodus-linux-x64-*.zip

# install Exodus
sudo ln -s $SRC/Exodus-linux-x64/Exodus /usr/local/bin/Exodus
sudo chmod +x /usr/local/bin/Exodus

# copy dependencies from Electrum to Electron Cash
mkdir electron-cash/packages/
cp electrum/packages/* electron-cash/packages/ -R

mkdir electrum-ltc/packages/
cp electrum/packages/* electrum-ltc/packages/ -R
pyrcc5 electrum-ltc/icons.qrc -o electrum-ltc/gui/qt/icons_rc.py