#!/bin/bash -e

HELP=/usr/local/share/doc/bitkey-help
LIB=/usr/local/lib
SHARE=/usr/local/share
SRC=/usr/local/src

cd $SRC
tar -xf firefox-*.tar.bz2
rm firefox-*.tar.bz2
mv firefox/ $LIB/firefox/
sudo ln -s $LIB/firefox/firefox /usr/local/bin/firefox

tar -zxf $SRC/zxcvbn/libs.tar.gz -C $SHARE/zxcvbn
rm $SRC/zxcvbn/libs.tar.gz

tar -zxf $SRC/qrcode/libs.tar.gz -C $SHARE/qrcode
rm $SRC/qrcode/libs.tar.gz

unzip bip39-*.zip
rm bip39-*.zip
mv bip39-*/ $SHARE/bip39/

unzip minimalist-ripple-client.zip
rm minimalist-ripple-client.zip
mkdir $SHARE/minripple/
mv minimalist-ripple-client.html $SHARE/minripple/

unzip iota-paper-wallet.zip 
rm iota-paper-wallet.zip
mv iota-paper-wallet/ $SHARE/iotapaperwallet 

unzip iota-seedgen.zip
rm iota-seedgen.zip
mkdir $SHARE/iotaseedgen/
mv iota-seedgen.html $SHARE/iotaseedgen/

unzip bitaddress.org*.zip
rm bitaddress.org*.zip
mv bitaddress.org*/ $SHARE/bitaddress.org/

unzip bitcoinpaperwallet-master.zip
rm bitcoinpaperwallet-master.zip
mv bitcoinpaperwallet-master/ $SHARE/bitcoinpaperwallet/

mkdir $SHARE/warpwallet/
unzip warp_*.zip
mv warp_*.html $SHARE/warpwallet/warpwallet.html

unzip coinbin-*.zip
rm coinbin-*.zip
mv coinbin-*/ $SHARE/coinbin/

unzip etherwallet*.zip
mv etherwallet*/ $SHARE/myetherwallet/
rm etherwallet*.zip

tar -zxf $HELP/assets.tar.gz -C $HELP
rm $HELP/assets.tar.gz