#!/bin/bash -e

SRC=/usr/local/src

tar -zxf $SRC/zxcvbn/libs.tar.gz -C $SRC/zxcvbn
rm $SRC/zxcvbn/libs.tar.gz

tar -zxf $SRC/qrcode/libs.tar.gz -C $SRC/qrcode
rm $SRC/qrcode/libs.tar.gz

unzip $SRC/bitaddress.org*.zip -d $SRC
rm $SRC/bitaddress.org*.zip
mv $SRC/bitaddress.org* $SRC/bitaddress.org

HELP=/usr/local/share/doc/bitkey-help
tar -zxf $HELP/assets.tar.gz -C $HELP
rm $HELP/assets.tar.gz

cd $SRC/warpwallet
ln -sf warp_*.html index.html

