#!/bin/bash -e

GSET="sudo -u user dbus-launch --exit-with-session gsettings set"

SCHEMA=org.gnome.desktop.interface
$GSET $SCHEMA cursor-theme 'DMZ-White'
$GSET $SCHEMA gtk-theme 'Zukitwo'

SCHEMA=org.gnome.desktop.wm.preferences
$GSET $SCHEMA theme 'Zukitwo'
$GSET $SCHEMA titlebar-uses-system-font true

SCHEMA=org.gnome.desktop.wm.keybindings
$GSET $SCHEMA panel-main-menu "[]"
$GSET $SCHEMA panel-run-dialog "[]"
$GSET $SCHEMA unmaximize "[]"
$GSET $SCHEMA activate-window-menu "['<Alt>F3']"
$GSET $SCHEMA cycle-windows "['<Ctrl>Tab']"
$GSET $SCHEMA maximize-horizontally "['<Super>w']"
$GSET $SCHEMA maximize-vertically "['<Super>s']"
$GSET $SCHEMA minimize "['<Alt>F9']"
$GSET $SCHEMA move-to-center "['<Super><Shift>space']"
$GSET $SCHEMA move-to-side-e "['<Super><Shift>l','<Super><Shift>Right']"
$GSET $SCHEMA move-to-side-n "['<Super><Shift>k','<Super><Shift>Up']"
$GSET $SCHEMA move-to-side-s "['<Super><Shift>j','<Super><Shift>Down']"
$GSET $SCHEMA move-to-side-w "['<Super><Shift>h','<Super><Shift>Left']"
$GSET $SCHEMA move-to-workspace-1 "['<Super><Shift>F1']"
$GSET $SCHEMA move-to-workspace-2 "['<Super><Shift>F2']"
$GSET $SCHEMA move-to-workspace-3 "['<Super><Shift>F3']"
$GSET $SCHEMA move-to-workspace-4 "['<Super><Shift>F4']"
$GSET $SCHEMA switch-to-workspace-1 "['<Super>F1']"
$GSET $SCHEMA switch-to-workspace-2 "['<Super>F2']"
$GSET $SCHEMA switch-to-workspace-3 "['<Super>F3']"
$GSET $SCHEMA switch-to-workspace-4 "['<Super>F4']"
$GSET $SCHEMA toggle-maximized "['<Alt>F10']"
$GSET $SCHEMA toggle-on-all-workspaces "['<Alt>F11']"

# update db for overlayed desktop files
update-desktop-database
