#!/bin/sh

PREREQ=""
DESCRIPTION="Setup system for offline mode..."

grep -qs offline-mode /proc/cmdline || exit 0

. /scripts/casper-functions

prereqs()
{
    echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
    prereqs
    exit 0
    ;;
esac

if [ -e /root/usr/lib/offline-mode ]; then
    log_begin_msg "$DESCRIPTION"
    mount -t proc proc-chroot /root/proc
    chroot /root sh -c "run-parts /usr/lib/offline-mode"
    umount /root/proc
    log_end_msg
fi

exit 0
