#!/bin/sh

MASTERPASS=$(mcookie | cut --bytes 1-8)

cat>/etc/inithooks.conf<<EOF
export ROOT_PASS=$MASTERPASS
export USER_PASS=$MASTERPASS
export SEC_UPDATES=SKIP
export HUB_APIKEY=SKIP
export SEC_ALERTS=SKIP
EOF

