#!/bin/sh

mode=$1
CONFIG=/home/user/.wbar

cat >$CONFIG<<EOF
i: /usr/share/pixmaps/wbar/dock.png
c: wbar --bpress --pos bottom --zoomf 1.3 --isize 52 --idist 3 --jumpf 1 --nanim 3 --balfa 25
t: /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf/10

i: /usr/local/share/icons/electrum.png
c: electrum-wrapper $mode >/dev/null
t: Electrum ($mode)

i: /usr/local/share/electrum-ltc/icons/electrum-ltc.png
c: electrum-ltc-wrapper $mode >/dev/null
t: Electrum-LTC ($mode)

i: /usr/local/share/electron-cash/icons/electron_launcher.png
c: electron-cash-wrapper $mode >/dev/null
t: Electron Cash ($mode)

i: /usr/local/share/icons/electrum-dash.png
c: electrum-dash-wrapper $mode >/dev/null
t: Electrum-Dash ($mode)

i: /usr/local/share/icons/exodus.png
c: exodus-wrapper >/dev/null
t: Exodus

i: /usr/local/share/icons/armoryicon.png
c: armory-wrapper >/dev/null
t: Armory ($mode)

i: /usr/local/share/icons/paper-wallet.png
c: chromium-offline-app file:///usr/local/share/cryptojsappslauncher/offline.html
t: Offline Web Apps

EOF

if [ ! "$mode" = "cold-offline" ]; then
cat >>$CONFIG<<EOF
i: /usr/local/share/icons/wallet.png
c: chromium-online-app file:///usr/local/share/cryptojsappslauncher/online.html
t: Online Web Apps

i: /usr/share/pixmaps/chromium.png
c: chromium-wrapper
t: Web browser

EOF
fi

cat >>$CONFIG<<EOF
i: /usr/share/pixmaps/qtqr.png
c: qtqr
t: QR scanner

i: /usr/share/icons/Adwaita/48x48/emblems/emblem-readonly.png
c: cryptoseed
t: CryptoSeed

i: /usr/share/icons/hicolor/128x128/apps/keepassx.png
c: keepassxc
t: KeePassXC

i: /usr/share/icons/gnome/48x48/apps/terminal.png
c: mrxvt
t: terminal

i: /usr/share/icons/gnome/48x48/apps/accessories-text-editor.png
c: gvim -y -n
t: editor

i: /usr/share/icons/gnome/48x48/devices/keyboard.png
c: florence
t: keyboard

i: /usr/share/icons/gnome/48x48/apps/file-manager.png
c: thunar /media
t: file manager

i: /usr/share/icons/gnome/48x48/devices/printer.png
c: /usr/bin/system-config-printer
t: printer

EOF

if [ ! "$mode" = "cold-offline" ]; then
cat >>$CONFIG<<EOF
i: /usr/share/icons/gnome/48x48/devices/network-wireless.png
c: wicd-client --no-tray
t: network

EOF
fi

cat >>$CONFIG<<EOF
i: /usr/share/icons/gnome/48x48/actions/system-shutdown.png
c: shutdown-prompt
t: shutdown

EOF

