#!/bin/sh

mode=$1
CONFIG=/home/user/.wbar

cat >$CONFIG<<EOF
i: /usr/share/pixmaps/wbar/dock.png
c: wbar --bpress --pos bottom --zoomf 1.3 --isize 72 --idist 4 --jumpf 1 --nanim 3 --balfa 25
t: /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf/10

i: /usr/local/share/icons/electrum.png
c: electrum-wrapper $mode >/dev/null
t: electrum ($mode)

i: /usr/local/src/electrum-ltc/icons/electrum-ltc.png
c: electrum-ltc
t: electrum-ltc

i: /usr/local/src/electron-cash/icons/electron_launcher.png
c: electron-cash
t: electron-cash

i: /usr/local/src/etherwallet-v3.10.9.2/images/icons/icon192.png
c: chromium-offline-app file:///usr/local/src/etherwallet-v3.10.9.2/index.html
t: my ether wallet

EOF

if [ ! "$mode" = "cold-offline" ]; then
cat >>$CONFIG<<EOF
i: /usr/share/pixmaps/chromium.png
c: chromium-wrapper
t: browser

EOF
fi

cat >>$CONFIG<<EOF
i: /usr/local/src/warpwallet/icon.png
c: chromium-offline-app file:///usr/local/src/warpwallet/index.html
t: warpwallet

i: /usr/share/icons/gnome/48x48/apps/fonts.png
c: chromium-offline-app file:///usr/local/src/bitaddress.org/bitaddress.org.html
t: bitaddress

i: /usr/local/src/bitcoinpaperwallet/paper-wallet.png
c: chromium-offline-app file:///usr/local/src/bitcoinpaperwallet/generate-wallet.html
t: bitpaper

i: /usr/local/share/icons/qrcode.png
c: chromium-offline-app file:///usr/local/src/qrcode/index.html
t: qrcode generator

i: /usr/local/share/icons/qrscan.png
c: chromium-offline-app file:///usr/local/src/webqr/webqr.html
t: qrcode scanner

i: /usr/share/icons/gnome/48x48/status/stock_lock.png
c: chromium-offline-app file:///usr/local/src/zxcvbn/index.html
t: password strength

i: /usr/local/src/coinbin/icon.png
c: chromium-online-app file:///usr/local/src/coinbin/index.html
t: coinbin

i: /usr/share/icons/gnome/48x48/apps/terminal.png
c: mrxvt
t: terminal

i: /usr/share/icons/gnome/48x48/apps/accessories-text-editor.png
c: gvim -y -n
t: editor

i: /usr/share/icons/gnome/48x48/devices/keyboard.png
c: florence
t: keyboard

i: /usr/share/icons/gnome/48x48/apps/file-manager.png
c: thunar /media
t: file manager

i: /usr/share/icons/gnome/48x48/devices/printer.png
c: /usr/bin/system-config-printer
t: printer

EOF

if [ ! "$mode" = "cold-offline" ]; then
cat >>$CONFIG<<EOF
i: /usr/share/icons/gnome/48x48/devices/network-wireless.png
c: wicd-client --no-tray
t: network

EOF
fi

cat >>$CONFIG<<EOF
i: /usr/share/icons/gnome/48x48/actions/system-shutdown.png
c: shutdown-prompt
t: shutdown

EOF

